[[redirects]]
  from = "/proxy/naver_stock"
  to = "https://m.stock.naver.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/proxy/naver_trend"
  to = "https://openapi.naver.com/:splat"
  status = 200
  force = true
